export type Country = {
  code: string;
  name: string;
  flag: string;
};

function codeToFlag(code: string): string {
  return String.fromCodePoint(
    ...code
      .toUpperCase()
      .split("")
      .map((c) => 0x1f1e6 + c.charCodeAt(0) - 65)
  );
}

function c(code: string, name: string): Country {
  return { code, name, flag: codeToFlag(code) };
}

export const countries: Country[] = [
  c("AF", "Afghanistan"),
  c("AX", "Åland Islands"),
  c("AL", "Albania"),
  c("DZ", "Algeria"),
  c("AS", "American Samoa"),
  c("AD", "Andorra"),
  c("AO", "Angola"),
  c("AI", "Anguilla"),
  c("AQ", "Antarctica"),
  c("AG", "Antigua and Barbuda"),
  c("AR", "Argentina"),
  c("AM", "Armenia"),
  c("AW", "Aruba"),
  c("AU", "Australia"),
  c("AT", "Austria"),
  c("AZ", "Azerbaijan"),
  c("BS", "Bahamas"),
  c("BH", "Bahrain"),
  c("BD", "Bangladesh"),
  c("BB", "Barbados"),
  c("BY", "Belarus"),
  c("BE", "Belgium"),
  c("BZ", "Belize"),
  c("BJ", "Benin"),
  c("BM", "Bermuda"),
  c("BT", "Bhutan"),
  c("BO", "Bolivia"),
  c("BQ", "Bonaire, Sint Eustatius and Saba"),
  c("BA", "Bosnia and Herzegovina"),
  c("BW", "Botswana"),
  c("BV", "Bouvet Island"),
  c("BR", "Brazil"),
  c("IO", "British Indian Ocean Territory"),
  c("BN", "Brunei Darussalam"),
  c("BG", "Bulgaria"),
  c("BF", "Burkina Faso"),
  c("BI", "Burundi"),
  c("CV", "Cabo Verde"),
  c("KH", "Cambodia"),
  c("CM", "Cameroon"),
  c("CA", "Canada"),
  c("KY", "Cayman Islands"),
  c("CF", "Central African Republic"),
  c("TD", "Chad"),
  c("CL", "Chile"),
  c("CN", "China"),
  c("CX", "Christmas Island"),
  c("CC", "Cocos (Keeling) Islands"),
  c("CO", "Colombia"),
  c("KM", "Comoros"),
  c("CG", "Congo"),
  c("CD", "Congo, Democratic Republic of the"),
  c("CK", "Cook Islands"),
  c("CR", "Costa Rica"),
  c("CI", "Côte d'Ivoire"),
  c("HR", "Croatia"),
  c("CU", "Cuba"),
  c("CW", "Curaçao"),
  c("CY", "Cyprus"),
  c("CZ", "Czechia"),
  c("DK", "Denmark"),
  c("DJ", "Djibouti"),
  c("DM", "Dominica"),
  c("DO", "Dominican Republic"),
  c("EC", "Ecuador"),
  c("EG", "Egypt"),
  c("SV", "El Salvador"),
  c("GQ", "Equatorial Guinea"),
  c("ER", "Eritrea"),
  c("EE", "Estonia"),
  c("SZ", "Eswatini"),
  c("ET", "Ethiopia"),
  c("FK", "Falkland Islands"),
  c("FO", "Faroe Islands"),
  c("FJ", "Fiji"),
  c("FI", "Finland"),
  c("FR", "France"),
  c("GF", "French Guiana"),
  c("PF", "French Polynesia"),
  c("TF", "French Southern Territories"),
  c("GA", "Gabon"),
  c("GM", "Gambia"),
  c("GE", "Georgia"),
  c("DE", "Germany"),
  c("GH", "Ghana"),
  c("GI", "Gibraltar"),
  c("GR", "Greece"),
  c("GL", "Greenland"),
  c("GD", "Grenada"),
  c("GP", "Guadeloupe"),
  c("GU", "Guam"),
  c("GT", "Guatemala"),
  c("GG", "Guernsey"),
  c("GN", "Guinea"),
  c("GW", "Guinea-Bissau"),
  c("GY", "Guyana"),
  c("HT", "Haiti"),
  c("HM", "Heard Island and McDonald Islands"),
  c("VA", "Holy See"),
  c("HN", "Honduras"),
  c("HK", "Hong Kong"),
  c("HU", "Hungary"),
  c("IS", "Iceland"),
  c("IN", "India"),
  c("ID", "Indonesia"),
  c("IR", "Iran"),
  c("IQ", "Iraq"),
  c("IE", "Ireland"),
  c("IM", "Isle of Man"),
  c("IL", "Israel"),
  c("IT", "Italy"),
  c("JM", "Jamaica"),
  c("JP", "Japan"),
  c("JE", "Jersey"),
  c("JO", "Jordan"),
  c("KZ", "Kazakhstan"),
  c("KE", "Kenya"),
  c("KI", "Kiribati"),
  c("KP", "Korea, Democratic People's Republic of"),
  c("KR", "Korea, Republic of"),
  c("KW", "Kuwait"),
  c("KG", "Kyrgyzstan"),
  c("LA", "Lao People's Democratic Republic"),
  c("LV", "Latvia"),
  c("LB", "Lebanon"),
  c("LS", "Lesotho"),
  c("LR", "Liberia"),
  c("LY", "Libya"),
  c("LI", "Liechtenstein"),
  c("LT", "Lithuania"),
  c("LU", "Luxembourg"),
  c("MO", "Macao"),
  c("MG", "Madagascar"),
  c("MW", "Malawi"),
  c("MY", "Malaysia"),
  c("MV", "Maldives"),
  c("ML", "Mali"),
  c("MT", "Malta"),
  c("MH", "Marshall Islands"),
  c("MQ", "Martinique"),
  c("MR", "Mauritania"),
  c("MU", "Mauritius"),
  c("YT", "Mayotte"),
  c("MX", "Mexico"),
  c("FM", "Micronesia"),
  c("MD", "Moldova"),
  c("MC", "Monaco"),
  c("MN", "Mongolia"),
  c("ME", "Montenegro"),
  c("MS", "Montserrat"),
  c("MA", "Morocco"),
  c("MZ", "Mozambique"),
  c("MM", "Myanmar"),
  c("NA", "Namibia"),
  c("NR", "Nauru"),
  c("NP", "Nepal"),
  c("NL", "Netherlands"),
  c("NC", "New Caledonia"),
  c("NZ", "New Zealand"),
  c("NI", "Nicaragua"),
  c("NE", "Niger"),
  c("NG", "Nigeria"),
  c("NU", "Niue"),
  c("NF", "Norfolk Island"),
  c("MK", "North Macedonia"),
  c("MP", "Northern Mariana Islands"),
  c("NO", "Norway"),
  c("OM", "Oman"),
  c("PK", "Pakistan"),
  c("PW", "Palau"),
  c("PS", "Palestine"),
  c("PA", "Panama"),
  c("PG", "Papua New Guinea"),
  c("PY", "Paraguay"),
  c("PE", "Peru"),
  c("PH", "Philippines"),
  c("PN", "Pitcairn"),
  c("PL", "Poland"),
  c("PT", "Portugal"),
  c("PR", "Puerto Rico"),
  c("QA", "Qatar"),
  c("RE", "Réunion"),
  c("RO", "Romania"),
  c("RU", "Russia"),
  c("RW", "Rwanda"),
  c("BL", "Saint Barthélemy"),
  c("SH", "Saint Helena, Ascension and Tristan da Cunha"),
  c("KN", "Saint Kitts and Nevis"),
  c("LC", "Saint Lucia"),
  c("MF", "Saint Martin"),
  c("PM", "Saint Pierre and Miquelon"),
  c("VC", "Saint Vincent and the Grenadines"),
  c("WS", "Samoa"),
  c("SM", "San Marino"),
  c("ST", "São Tomé and Príncipe"),
  c("SA", "Saudi Arabia"),
  c("SN", "Senegal"),
  c("RS", "Serbia"),
  c("SC", "Seychelles"),
  c("SL", "Sierra Leone"),
  c("SG", "Singapore"),
  c("SX", "Sint Maarten"),
  c("SK", "Slovakia"),
  c("SI", "Slovenia"),
  c("SB", "Solomon Islands"),
  c("SO", "Somalia"),
  c("ZA", "South Africa"),
  c("GS", "South Georgia and the South Sandwich Islands"),
  c("SS", "South Sudan"),
  c("ES", "Spain"),
  c("LK", "Sri Lanka"),
  c("SD", "Sudan"),
  c("SR", "Suriname"),
  c("SJ", "Svalbard and Jan Mayen"),
  c("SE", "Sweden"),
  c("CH", "Switzerland"),
  c("SY", "Syria"),
  c("TW", "Taiwan"),
  c("TJ", "Tajikistan"),
  c("TZ", "Tanzania"),
  c("TH", "Thailand"),
  c("TL", "Timor-Leste"),
  c("TG", "Togo"),
  c("TK", "Tokelau"),
  c("TO", "Tonga"),
  c("TT", "Trinidad and Tobago"),
  c("TN", "Tunisia"),
  c("TR", "Turkey"),
  c("TM", "Turkmenistan"),
  c("TC", "Turks and Caicos Islands"),
  c("TV", "Tuvalu"),
  c("UG", "Uganda"),
  c("UA", "Ukraine"),
  c("AE", "United Arab Emirates"),
  c("GB", "United Kingdom"),
  c("US", "United States"),
  c("UM", "United States Minor Outlying Islands"),
  c("UY", "Uruguay"),
  c("UZ", "Uzbekistan"),
  c("VU", "Vanuatu"),
  c("VE", "Venezuela"),
  c("VN", "Vietnam"),
  c("VG", "Virgin Islands, British"),
  c("VI", "Virgin Islands, U.S."),
  c("WF", "Wallis and Futuna"),
  c("EH", "Western Sahara"),
  c("YE", "Yemen"),
  c("ZM", "Zambia"),
  c("ZW", "Zimbabwe"),
].sort((a, b) => a.name.localeCompare(b.name));
